=== Terradue/Stars/src/Stars.Data.Tests/Resources/CSA/RCM-1/GCD/data/RCM1_OK1052791_PK1052796_1_3MCP24_20200219_123901_CH_CV_GCD/support/schemas/rcm_prod_noiseLevels.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- edited with XMLSpy v2015 sp2 (x64) (http://www.altova.com) by jkuo (MDA SYSTEMS LTD) -->
<!--=========================================================================
Filename      : rcm_prod_noiseLevels.xsd@@/main/10 ( Pitt: 37461 )
Project       : RCM-GS
Module        : PGS - Product Metadata Generator
Document Type : XSD
Purpose       : Data Store Schema definition

(C) Copyright 2015 MacDonald, Dettwiler and Associates Ltd. and/or its affiliates. All Rights Reserved.

Author        Date          Changes
J. Kuo        17-Nov-2015   Original Definition RCM-SP-53-0419 Issue 2/0
E. Jenkins    22-May-2016   Consolidated schema files
E. Jenkins    11-Aug-2016   Updates for RCM-SP-53-0419 Issue 2/2
C. Vigneron   28-Oct-2016   Update stepSize description 
C. Vigneron   08-Mar-2017   Updates for RCM-SP-53-0419 Issue 2/3
J. Chiang     31-Jul-2017   Updates for RCM-SP-53-0419 Issue 2/4
=============================================================================-->
<!-- 67890123456789012345678901234567890123456789012345678901234567890123456 -->
<xsd:schema xmlns:rcm_prod="rcmGsProductSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="rcmGsProductSchema" elementFormDefault="qualified">
	<xsd:include schemaLocation="rcm_prod_units.xsd"/>
	<xsd:include schemaLocation="rcm_prod_identifiers.xsd"/>
	<xsd:include schemaLocation="rcm_prod_lists.xsd"/>

	<xsd:group name="referenceNoiseLevelCommon">
		<xsd:annotation>
			<xsd:documentation> 
      Reference Noise Level Common Elements
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
		    <xsd:element name="sarCalibrationType" type="rcm_prod:sarCalibrationTypeIdentifiers">
				<xsd:annotation>
					<xsd:documentation>"Beta Nought", "Sigma Nought", or "Gamma".
                    </xsd:documentation>
				</xsd:annotation>
		    </xsd:element>
			<xsd:element name="pixelFirstNoiseValue" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation>Pixel number corresponding to first noise value.
The pixel is indexed from the leftmost range sample of the full range line and starts with ‘0’ with respect to the range start of the COPG. 
          </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="stepSize" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation>Number of range pixels between noiseLevelValues entries. The sign of stepSize (positive or negative) depends on pixelTimeOrdering which indicates the samples increase or decrease with range time order.
          </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="numberOfValues" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation>Number of entries in noiseLevelValues. 
          </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="noiseLevelValues">
				<xsd:annotation>
					<xsd:documentation>Estimated noise level values as a function of georeferenced image pixel position in range.  (units = dB)
          				</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="rcm_prod:noiseLevelValuesList">
							<xsd:attribute name="units" type="rcm_prod:powerUnits" use="required" fixed="dB"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:group>

    <xsd:complexType name="referenceNoiseLevelDataStore">
		<xsd:annotation>
			<xsd:documentation> 
      Per Beam Reference Noise Level Data Store
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
            <xsd:group ref="rcm_prod:referenceNoiseLevelCommon"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="perBeamReferenceNoiseLevelDataStore">
		<xsd:annotation>
			<xsd:documentation> 
      Per Beam Reference Noise Level Data Store
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
		    <xsd:element name="beam" type="rcm_prod:beamList">
		        <xsd:annotation>
			        <xsd:documentation>Beam for this record. Values are same as those used in the beam list.</xsd:documentation>
		        </xsd:annotation>
		    </xsd:element>
            <xsd:group ref="rcm_prod:referenceNoiseLevelCommon"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="azimuthNoiseLevelScalingDataStore">
		<xsd:annotation>
			<xsd:documentation> 
      Azimuth Noise Level Scaling Factors Data Store
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
		    <xsd:element name="beam" type="rcm_prod:beamList">
		        <xsd:annotation>
			        <xsd:documentation>Beam for this record. Values are same as those used in the beam list.</xsd:documentation>
		        </xsd:annotation>
		    </xsd:element>
            <xsd:element name="lineFirstNoiseScalingValue" type="xsd:integer" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Line number corresponding to first noise scaling value.
The line is indexed from the first range line of the image from 0 to N-1. Applicable only for Spotlight products.
                    </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="stepSize" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation>Number of lines between noiseLevelScalingValues entries indicated by the absolute value of stepSize
The sign of stepSize (positive or negative) depends on lineTimeOrdering which indicates the samples increase or decrease with azimuth time order. 
                    </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="numberOfNoiseLevelScalingValues" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation>
            Number of entries in list
          </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="noiseLevelScalingValues">
				<xsd:annotation>
					<xsd:documentation>Scaling factors representing the azimuth dependence of the noise level at the mid-range point of an image burst (or, for Spotlight mode, at the mid-range point of an image) (units = dB). 
These scaling factors are not necessarily symmetric and are approximately centered about the middle of image burst (or image) in azimuth. </xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="rcm_prod:noiseLevelValuesList">
							<xsd:attribute name="units" type="rcm_prod:powerUnits" use="required" fixed="dB"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="noiseLevels">
		<xsd:annotation>
			<xsd:documentation> 
      Noise level information.
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="referenceNoiseLevel" type="rcm_prod:referenceNoiseLevelDataStore" minOccurs="0" maxOccurs="3">
					<xsd:annotation>
						<xsd:documentation>Estimated mean image noise levels as a function of georeferenced image pixel in range. One vector for beta nought, sigma nought, and gamma respectively.
For ScanSAR GRD products, if noise subtraction was performed, the beta-nought vector represents a first order approximation to the range dependent reference noise level that was used in the noise subtraction.
This field does not apply to ScanSAR SLC products. 
</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="perBeamReferenceNoiseLevel" type="rcm_prod:perBeamReferenceNoiseLevelDataStore" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>Estimated mean image noise levels as a function of georeferenced image pixel in range per beam. One vector for beta nought, sigma nought, and gamma respectively per beam.
For each beam, the beta-noulgt vector represents a first order approximation of the range dependent reference noise level.
This field is present only for ScanSAR SLC and ScanSAR GRD products.

            </xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="azimuthNoiseLevelScaling" type="rcm_prod:azimuthNoiseLevelScalingDataStore" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>For each beam, the estimated azimuth dependent scaling factors to be applied to the range dependent reference noise level.
This field is present only for Spotlight and single burst-mode products (ScanSAR and Single Beam Dual HH-VV Polarization mode). Note that for the Burst azimuth 2-look modes, the azimuth scaling is a constant vector due to the Bamler radiometric correction method.
For ScanSAR GRD products, If noise subtraction was performed, these represent a first order approximation to the azimuth dependent scaling factors that were applied. 
Note:
1) The noise values are defined at the mid-range point of the image (SL) or the burst at the middle cycle (Burst Mode GRD) while during the application of the noise subtraction, the processor actually uses azimuth dependent scaling factors that vary slowly with range.
2) The geometrical center of the reported azimuth noise level scaling factor is approximately aligned to the geometrical centre of a burst in azimuth.

</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Terradue/Stars/src/Stars.Data.Tests/Resources/CSA/RCM-2/GRD/data/RCM2_OK2116806_PK2116811_1_16M5_20220605_070317_HH_HV_GRD/metadata/calibration/noiseLevels_HH.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<noiseLevels xmlns="rcmGsProductSchema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="rcmGsProductSchema ../../support/schemas/rcm_prod_noiseLevels.xsd">
	<referenceNoiseLevel>
		<sarCalibrationType>Beta Nought</sarCalibrationType>
		<pixelFirstNoiseValue>4844</pixelFirstNoiseValue>
		<stepSize>-49</stepSize>
		<numberOfValues>100</numberOfValues>
		<noiseLevelValues units="dB">-2.636076688766479e+01 -2.648298025131226e+01 -2.660513877868652e+01 -2.671508312225342e+01 -2.682261228561401e+01 -2.693009376525879e+01 -2.702841281890869e+01 -2.712237119674683e+01 -2.721628665924072e+01 -2.730377435684204e+01 -2.738522529602051e+01 -2.746664047241211e+01 -2.754402637481689e+01 -2.761391401290894e+01 -2.768376588821411e+01 -2.775171995162964e+01 -2.781092166900635e+01 -2.787009477615356e+01 -2.792923688888550e+01 -2.797869443893433e+01 -2.802812814712524e+01 -2.807753562927246e+01 -2.811971187591553e+01 -2.816027879714966e+01 -2.820082426071167e+01 -2.823627948760986e+01 -2.826879262924194e+01 -2.830128908157349e+01 -2.833056688308716e+01 -2.835582733154297e+01 -2.838107347488403e+01 -2.840469598770142e+01 -2.842346191406250e+01 -2.844221591949463e+01 -2.846066713333130e+01 -2.847367525100708e+01 -2.848667144775391e+01 -2.849966049194336e+01 -2.850838899612427e+01 -2.851634025573730e+01 -2.852428436279297e+01 -2.852944135665894e+01 -2.853301763534546e+01 -2.853658914566040e+01 -2.853857517242432e+01 -2.853842735290527e+01 -2.853827714920044e+01 -2.853747606277466e+01 -2.853420734405518e+01 -2.853093385696411e+01 -2.852766036987305e+01 -2.852185249328613e+01 -2.851600646972656e+01 -2.851016044616699e+01 -2.850272893905640e+01 -2.849479675292969e+01 -2.848686218261719e+01 -2.847803354263306e+01 -2.846839904785156e+01 -2.845876455307007e+01 -2.844871759414673e+01 -2.843766212463379e+01 -2.842660665512085e+01 -2.841549158096313e+01 -2.840316295623779e+01 -2.839083433151245e+01 -2.837851047515869e+01 -2.836514472961426e+01 -2.835152626037598e+01 -2.833791255950928e+01 -2.832348346710205e+01 -2.830839872360229e+01 -2.829331636428833e+01 -2.827769041061401e+01 -2.826077222824097e+01 -2.824385881423950e+01 -2.822686195373535e+01 -2.820756196975708e+01 -2.818826913833618e+01 -2.816897869110107e+01 -2.814730167388916e+01 -2.812491416931152e+01 -2.810253381729126e+01 -2.807816505432129e+01 -2.805180311203003e+01 -2.802544832229614e+01 -2.799798250198364e+01 -2.796663999557495e+01 -2.793530941009521e+01 -2.790399074554443e+01 -2.786689996719360e+01 -2.782947778701782e+01 -2.779206752777100e+01 -2.774984121322632e+01 -2.770511627197266e+01 -2.766041040420532e+01 -2.761255979537964e+01 -2.755927801132202e+01 -2.750601768493652e+01 -2.745207071304321e+01</noiseLevelValues>
	</referenceNoiseLevel>
	<referenceNoiseLevel>
		<sarCalibrationType>Sigma Nought</sarCalibrationType>
		<pixelFirstNoiseValue>4844</pixelFirstNoiseValue>
		<stepSize>-49</stepSize>
		<numberOfValues>100</numberOfValues>
		<noiseLevelValues units="dB">-2.990595102310181e+01 -3.002403974533081e+01 -3.014207839965820e+01 -3.024791002273560e+01 -3.035133600234985e+01 -3.045471668243408e+01 -3.054894208908081e+01 -3.063881635665894e+01 -3.072865009307861e+01 -3.081206321716309e+01 -3.088944911956787e+01 -3.096680164337158e+01 -3.104013442993164e+01 -3.110597133636475e+01 -3.117178440093994e+01 -3.123569965362549e+01 -3.129087448120117e+01 -3.134602308273315e+01 -3.140115022659302e+01 -3.144659757614136e+01 -3.149202585220337e+01 -3.153743505477905e+01 -3.157562017440796e+01 -3.161220073699951e+01 -3.164876461029053e+01 -3.168024778366089e+01 -3.170879364013672e+01 -3.173732995986938e+01 -3.176265239715576e+01 -3.178396463394165e+01 -3.180526733398438e+01 -3.182495117187500e+01 -3.183978557586670e+01 -3.185461759567261e+01 -3.186915159225464e+01 -3.187824726104736e+01 -3.188733577728271e+01 -3.189642667770386e+01 -3.190125703811646e+01 -3.190532207489014e+01 -3.190938234329224e+01 -3.191066265106201e+01 -3.191036701202393e+01 -3.191007375717163e+01 -3.190820217132568e+01 -3.190420389175415e+01 -3.190020561218262e+01 -3.189556360244751e+01 -3.188845634460449e+01 -3.188135623931885e+01 -3.187426090240479e+01 -3.186463356018066e+01 -3.185497522354126e+01 -3.184532403945923e+01 -3.183409214019775e+01 -3.182236433029175e+01 -3.181064367294312e+01 -3.179803133010864e+01 -3.178462028503418e+01 -3.177121400833130e+01 -3.175740242004395e+01 -3.174258708953857e+01 -3.172777652740479e+01 -3.171291112899780e+01 -3.169683933258057e+01 -3.168077468872070e+01 -3.166471719741821e+01 -3.164762735366821e+01 -3.163028955459595e+01 -3.161295890808105e+01 -3.159482240676880e+01 -3.157603263854980e+01 -3.155725240707397e+01 -3.153793334960938e+01 -3.151732921600342e+01 -3.149673461914062e+01 -3.147606372833252e+01 -3.145309448242188e+01 -3.143013238906860e+01 -3.140718698501587e+01 -3.138185262680054e+01 -3.135581970214844e+01 -3.132979631423950e+01 -3.130178928375244e+01 -3.127179384231567e+01 -3.124181270599365e+01 -3.121072769165039e+01 -3.117577075958252e+01 -3.114082813262939e+01 -3.110590457916260e+01 -3.106521606445312e+01 -3.102419614791870e+01 -3.098319768905640e+01 -3.093738794326782e+01 -3.088908672332764e+01 -3.084080696105957e+01 -3.078938722610474e+01 -3.073254585266113e+01 -3.067572832107544e+01 -3.061822891235352e+01</noiseLevelValues>
	</referenceNoiseLevel>
	<referenceNoiseLevel>
		<sarCalibrationType>Gamma</sarCalibrationType>
		<pixelFirstNoiseValue>4844</pixelFirstNoiseValue>
		<stepSize>-49</stepSize>
		<numberOfValues>100</numberOfValues>
		<noiseLevelValues units="dB">-2.943380355834961e+01 -2.955089187622070e+01 -2.966792297363281e+01 -2.977275085449219e+01 -2.987517356872559e+01 -2.997754669189453e+01 -3.007076454162598e+01 -3.015962982177734e+01 -3.024845504760742e+01 -3.033086013793945e+01 -3.040723800659180e+01 -3.048357963562012e+01 -3.055589866638184e+01 -3.062072372436523e+01 -3.068552207946777e+01 -3.074842453002930e+01 -3.080258369445801e+01 -3.085671615600586e+01 -3.091082763671875e+01 -3.095525741577148e+01 -3.099966812133789e+01 -3.104405975341797e+01 -3.108122634887695e+01 -3.111678314208984e+01 -3.115232658386230e+01 -3.118278884887695e+01 -3.121031188964844e+01 -3.123782348632812e+01 -3.126212310791016e+01 -3.128240966796875e+01 -3.130268859863281e+01 -3.132134628295898e+01 -3.133515357971191e+01 -3.134895706176758e+01 -3.136246109008789e+01 -3.137052726745605e+01 -3.137858963012695e+01 -3.138664627075195e+01 -3.139044761657715e+01 -3.139347839355469e+01 -3.139650535583496e+01 -3.139675140380859e+01 -3.139542007446289e+01 -3.139409255981445e+01 -3.139118385314941e+01 -3.138614845275879e+01 -3.138111305236816e+01 -3.137543487548828e+01 -3.136728668212891e+01 -3.135914802551270e+01 -3.135101127624512e+01 -3.134034156799316e+01 -3.132964134216309e+01 -3.131894874572754e+01 -3.130667114257812e+01 -3.129389953613281e+01 -3.128113555908203e+01 -3.126747512817383e+01 -3.125301742553711e+01 -3.123856544494629e+01 -3.122370719909668e+01 -3.120783996582031e+01 -3.119198036193848e+01 -3.117606735229492e+01 -3.115894317626953e+01 -3.114182662963867e+01 -3.112471771240234e+01 -3.110657119750977e+01 -3.108818054199219e+01 -3.106979751586914e+01 -3.105060577392578e+01 -3.103075981140137e+01 -3.101092338562012e+01 -3.099054527282715e+01 -3.096888351440430e+01 -3.094722938537598e+01 -3.092549896240234e+01 -3.090147018432617e+01 -3.087744712829590e+01 -3.085343933105469e+01 -3.082704353332520e+01 -3.079994583129883e+01 -3.077285766601562e+01 -3.074378776550293e+01 -3.071272659301758e+01 -3.068168258666992e+01 -3.064952850341797e+01 -3.061350250244141e+01 -3.057749176025391e+01 -3.054149818420410e+01 -3.049974250793457e+01 -3.045765113830566e+01 -3.041558265686035e+01 -3.036870002746582e+01 -3.031932830810547e+01 -3.026997566223145e+01 -3.021747970581055e+01 -3.015956497192383e+01 -3.010167121887207e+01 -3.004309654235840e+01</noiseLevelValues>
	</referenceNoiseLevel>
</noiseLevels>
